<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Testcontainers' Course: Specialized Containers</description>
    <name>specialized-containers</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ltc-specialized-containers</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>sql-databases-start</module>
        <module>sql-databases-end</module>
        <module>nosql-testing-start</module>
        <module>nosql-testing-end</module>
        <module>message-brokers-start</module>
        <module>message-brokers-end</module>
    </modules>
</project>
